### ISSUE TITLE
개발초기 환경 세팅을 한다

### ISSUE THREAD

**Issue by iamjunhyeong** [miniRT-however-we-are-largeRT/miniRT#2]
## Description
개발 초기 환경 세팅하기
### 변경 사항 제목
- [x] 이슈 템플릿
- [x] PR 템플릿
- [x] 파일 구조 설정
## API
| URL                | method | Usage                | Authorization Needed |
| ------------------ | ------ | -------------------- | -------------------- |
| api 경로       | POST| API 용도| 인가 필요성                    |
## Additional context
추가적인 내용

**Comment by doomangang** [comment]
Approved. ✅
